name: security-scan
on:
  push:
    branches: [ master ]

jobs:
  hello:
    runs-on: ubuntu-latest
    - name: hello

    run: |
          echo "Hello world :)"

  bandit:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SAST
      continue-on-error: true
      run: |
            mkdir reports 
            docker run --rm -v $(pwd):/data cytopia/bandit -r ./app -f txt -o test.txt
            
    - name: Archive bandit
        uses: actions/upload-artifact@v3
        with:
          name: test.txt
          path: reports/test.txt
    
