name: security-scan
on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    
    - name: hello
      run: | 
          echo "Hello world :)"

  bandit:
    runs-on: ubuntu-latest
    needs: hello

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SAST
      continue-on-error: true
      run: |
            mkdir reports 
            docker run --rm -v $(pwd):/data cytopia/bandit -r ./app -f txt -o reports/test.txt
            
    - name: Archive bandit
      uses: actions/upload-artifact@v3
      with:
          name: test.txt
          path: reports/test.txt
    
